const resList = [
  {
    type: "reastaurant",
    data: {
      id: 1,
      name: "KFC",
      cuisines: ["Burger", "Biryani", "American", "Snacks", "Fast Food"],
      costForTwo: 40000,
      avgRating: 4.4,
      deliveryTime: 27,
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    },
  },
  {
    type: "reastaurant",
    data: {
      id: 2,
      name: "KFC",
      cuisines: ["Burger", "Biryani", "American", "Snacks", "Fast Food"],
      costForTwo: 40000,
      avgRating: 4.4,
      deliveryTime: 27,
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    },
  },
  {
    type: "reastaurant",
    data: {
      id: 3,
      name: "KFC",
      cuisines: ["Burger", "Biryani", "American", "Snacks", "Fast Food"],
      costForTwo: 40000,
      avgRating: 4.4,
      deliveryTime: 27,
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    },
  },
  {
    type: "reastaurant",
    data: {
      id: 4,
      name: "KFC",
      cuisines: ["Burger", "Biryani", "American", "Snacks", "Fast Food"],
      costForTwo: 40000,
      avgRating: 4.4,
      deliveryTime: 27,
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    },
  },
  {
    type: "reastaurant",
    data: {
      id: 5,
      name: "KFC",
      cuisines: ["Burger", "Biryani", "American", "Snacks", "Fast Food"],
      costForTwo: 40000,
      avgRating: 4.4,
      deliveryTime: 27,
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    },
  },
  {
    type: "reastaurant",
    data: {
      id: 6,
      name: "KFC",
      cuisines: ["Burger", "Biryani", "American", "Snacks", "Fast Food"],
      costForTwo: 40000,
      avgRating: 4.4,
      deliveryTime: 27,
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    },
  },
  {
    type: "reastaurant",
    data: {
      id: 7,
      name: "KFC",
      cuisines: ["Burger", "Biryani", "American", "Snacks", "Fast Food"],
      costForTwo: 40000,
      avgRating: 4.4,
      deliveryTime: 27,
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    },
  },
  {
    type: "reastaurant",
    data: {
      id: 8,
      name: "KFC",
      cuisines: ["Burger", "Biryani", "American", "Snacks", "Fast Food"],
      costForTwo: 40000,
      avgRating: 4.4,
      deliveryTime: 27,
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    },
  },
  {
    type: "reastaurant",
    data: {
      id: 9,
      name: "KFC",
      cuisines: ["Burger", "Biryani", "American", "Snacks", "Fast Food"],
      costForTwo: 40000,
      avgRating: 4.4,
      deliveryTime: 27,
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    },
  },
  {
    type: "reastaurant",
    data: {
      id: 10,
      name: "KFC",
      cuisines: ["Burger", "Biryani", "American", "Snacks", "Fast Food"],
      costForTwo: 40000,
      avgRating: 4.4,
      deliveryTime: 27,
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    },
  },
  {
    type: "reastaurant",
    data: {
      id: 11,
      name: "KFC",
      cuisines: ["Burger", "Biryani", "American", "Snacks", "Fast Food"],
      costForTwo: 40000,
      avgRating: 4.4,
      deliveryTime: 27,
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    },
  },
  {
    type: "reastaurant",
    data: {
      id: 12,
      name: "KFC",
      cuisines: ["Burger", "Biryani", "American", "Snacks", "Fast Food"],
      costForTwo: 40000,
      avgRating: 4.4,
      deliveryTime: 27,
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    },
  },
  {
    type: "reastaurant",
    data: {
      id: 13,
      name: "KFC",
      cuisines: ["Burger", "Biryani", "American", "Snacks", "Fast Food"],
      costForTwo: 40000,
      avgRating: 4.4,
      deliveryTime: 27,
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    },
  },
  {
    type: "reastaurant",
    data: {
      id: 14,
      name: "KFC",
      cuisines: ["Burger", "Biryani", "American", "Snacks", "Fast Food"],
      costForTwo: 40000,
      avgRating: 4.4,
      deliveryTime: 27,
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    },
  },
  {
    type: "reastaurant",
    data: {
      id: 15,
      name: "KFC",
      cuisines: ["Burger", "Biryani", "American", "Snacks", "Fast Food"],
      costForTwo: 40000,
      avgRating: 4.4,
      deliveryTime: 27,
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    },
  },
  {
    type: "reastaurant",
    data: {
      id: 16,
      name: "KFC",
      cuisines: ["Burger", "Biryani", "American", "Snacks", "Fast Food"],
      costForTwo: 40000,
      avgRating: 4.4,
      deliveryTime: 27,
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    },
  },
  {
    type: "reastaurant",
    data: {
      id: 17,
      name: "KFC",
      cuisines: ["Burger", "Biryani", "American", "Snacks", "Fast Food"],
      costForTwo: 40000,
      avgRating: 4.4,
      deliveryTime: 27,
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    },
  },
  {
    type: "reastaurant",
    data: {
      id: 18,
      name: "KFC",
      cuisines: ["Burger", "Biryani", "American", "Snacks", "Fast Food"],
      costForTwo: 40000,
      avgRating: 4.4,
      deliveryTime: 27,
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    },
  },
  {
    type: "reastaurant",
    data: {
      id: 19,
      name: "KFC",
      cuisines: ["Burger", "Biryani", "American", "Snacks", "Fast Food"],
      costForTwo: 40000,
      avgRating: 4.4,
      deliveryTime: 27,
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    },
  },
  {
    type: "reastaurant",
    data: {
      id: 20,
      name: "KFC",
      cuisines: ["Burger", "Biryani", "American", "Snacks", "Fast Food"],
      costForTwo: 40000,
      avgRating: 4.4,
      deliveryTime: 27,
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    },
  },
];
export default resList;
